# Generated by Django 4.1.7 on 2023-03-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_basketballcategory_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketballcategory',
            options={'verbose_name': 'Бакстебольный чемпионат', 'verbose_name_plural': 'Бакстебольные чемпионаты'},
        ),
        migrations.AlterModelOptions(
            name='footballcategory',
            options={'verbose_name': 'Футбольный Чемпионат', 'verbose_name_plural': 'Футбольные Чемпионаты'},
        ),
        migrations.AlterModelOptions(
            name='hockeycategory',
            options={'verbose_name': 'Хоккейный чемпионат', 'verbose_name_plural': 'Хоккейные чемпионаты'},
        ),
    ]
